- .babelrc
- package.json
- src/App.vue
- src/components/Dashboard/Charts/LineChartPortfolio.vue
- src/components/Dashboard/Charts/LineChartTable.vue
- src/components/Dashboard/DashboardChart.vue
- src/components/Dashboard/DashboardDonutChart.vue
- src/components/Dashboard/DashboardPage.vue
- src/components/Dashboard/DashboardPortfolio.vue
- src/components/Dashboard/DashboardTable.vue
- src/components/Wallets/WalletsPage.vue
- src/components/mixins/dateFormat.js
- src/main.js
- src/router.js
- src/store/Account.js
- src/store/Dashboard.js
- src/store/Settings.js
- src/store/Wallet.js
- src/util/storage-util.js
- src/util/store-util.js
- vue.config.js
- yarn.lock
_Size_: 9.8 MB
Download: [report.html.zip](https://github.com/d3ledger/back-office/files/2227909/report.html.zip)
_Size_: 8 MB
this PR, because I can reduce size of the `moment` library. **(Size: 525 KB -> 125 KB)**
This is list of parts that still have big size
- `iroha-lib` - 4 MB
- `util\proto` - 430 KB
- `element-ui` - 944 KB
- `chart.js` - 345 KB
1. `yarn` to install new packages.
2. `yarn build:more-memory --report` - to build production version with report.
> Reduce bundle size

- src/util/iroha-util.js
Since Iroha supports status streaming now, I have replaced status request with status streaming. It should work better than 5sec waiting.
Try sending money. Please note that Iroha at our %secret-ip% isn't working now so please start local copy.
Since https://github.com/improbable-eng/grpc-web/pull/189 is not merged, if gRPC server hangs, in Google chrome uncaught exception happens and on(end) doesn't work. That's why I've using timeout there: to see if status requests aren't returning for some time. If grpc-web fix it, we can remove this code. (You can test this behaviour on our %secret-ip%).
> D3-284 | Streaming of TX statuses

- scripts/setup-accounts-and-assets.js
- src/components/Wallets/Wallet.vue
- yarn.lock
Added `yarn.lock` to #45 and added several fixes.
- yarn to install new packages.
- yarn serve to run dev server.
> fix: updated iroha-helpers v0.1.1

- package.json
- src/util/iroha-util.js
- yarn.lock
Since https://github.com/improbable-eng/grpc-web/pull/189 was merged and https://www.npmjs.com/package/grpc-web-client/v/0.6.3 was released, we need to fix TODO in `iroha-util` and remove "dirty hack": setTimeout. Now (if notary hangs) we can work properly with onEnd event.
Try sending transaction at our %secret-notary-ip% – it is hanged now :)
> D3-338 | Update grpc web

- src/App.vue
- src/components/Wallets/Wallet.vue
- src/main.js
- src/store/Wallet.js
- src/util/cryptoApi-axios-util.js
- tests/unit/store/Wallets.spec.js
Previously, a market widget in a wallet page used only `pricemultifull` API but it returned only today's or 24h values, therefore we couldn't see market data with other time ranges. In order to support other time ranges, I changed it to use also `histo{day,hour,minute}` and `exchange/histo{day,hour}` APIs and made it calculate the changes (B, D) and the total volumes (G, H) with these historical data.
* the change (${settingsView.fiat}) from today's open
* ⬇️ 
* the change (${settingsView.fiat}) from **${selectedMarketPeriod} ago**
* the change (%) from today's open
* ⬇️ 
* the change (%) from **${selectedMarketPeriod} ago**
* the amount ${wallet.asset} has been traded in 24 hours against ALL its trading pairs, in terms of ${settingsView.fiat}
* ⬇️ 
* the amount ${wallet.asset} has been …
> [D3-280] market widget

- src/components/Wallets/WalletMenuItem.vue
- src/components/Wallets/WalletsPage.vue
- src/main.js
- src/store/App.js
- tests/e2e/integration/wallets.spec.js
1. `yarn serve` and open the app
2. Go to the wallets page and try sorting
How the sort button works:
> [D3-279] wallet list

- scripts/setup-accounts-and-assets.js
- src/components/Home.vue
- src/components/Login.vue
- src/components/mixins/inputValidation.js
It allows you to send transactions with only one key.
1. `yarn serve` and open the app with test@notary whose quorum > 1.
2. Try to send some transactions with only one key.
> Allow sending transactions with only one key

- src/components/Home.vue
- src/components/Transactions/TransactionPage.vue
- src/store/Account.js
- src/util/iroha/commands.js
- src/util/iroha/queries.js
- src/util/store-util.js
- tests/unit/store/Account.spec.js
Now accounts with mulitsig (test@notary) can create transactions with not enough signatures and sign them later
1. `yarn && yarn serve`
2. login to `test@notary`, create transfer, enter only 1 key.
3. go to "transactions" page and sign this transaction with second key.
4. Check that transfer was successful on the "wallet" page.
1. Transaction doesn't disappear from pending and you can sign and send it again – problem in Iroha
2. No indication about current signatures of transaction – will be done in the next sprint.
3. If someone sends you a settlement, part of it will be displayed here – will be fixed in the "settlement" task.
4. When you create a transaction with only 1 key, it displays "transaction was send" - we will fix it later.
> D3-334, D3-234 | Pending transaction getting & signing

- src/components/Dashboard/Charts/LineChartPortfolio.vue
- src/components/Dashboard/DashboardPortfolio.vue
- src/main.js
- src/store/Dashboard.js
- src/util/cryptoApi-axios-util.js
- tests/unit/store/Dashboard.spec.js
Tooltip
Chart (RUB & 1Y)
Chart (EUR & 1H)
I tried to place xAxis inside as Zeplin does but it overlaps the line chart and yAxis 🤔 
1. `yarn server` and open the app.
2. Check the portfolio at the top of the dashboard page.
> [D3-276][D3-393] Portfolio's time range selection and tooltip

- src/components/Reports/ReportsPage.vue
- src/util/report-util.js
- tests/unit/fixtures/report.json
Make it able to generate a report until today. Use the last minute's close price (i.e. the latest price) as the today's price if today is within the range.
1. `yarn serve` and open the app.
2. Go to the report page and try today's report.
> A report until today

- src/util/notary-util.js
- tests/e2e/integration/auth.spec.js
- tests/unit/store/Account.spec.js
Capture a notary-util's error at a store action layer, not at a notary-util layer, and display the error on an alert.
1. `yarn serve` and open the app.
2. Try signing up in the environment that the app has no access to Notary. Signup should fail and an alert should appear.
> [D3-412] Handle registration failures

- src/App.vue
- src/components/Signup.vue
- src/main.js
- src/store/Account.js
- src/util/notary-util.js
- tests/unit/store/Account.spec.js
Add getter/setter of baseURL to notary-util and make the registration service ip changeable.
1. `yarn serve` and open the app.
2. Go to signup page and try changing the registration service IP. You can see if the IP is changed correctly at the Network pane.
> Make the registration service ip changeable

- src/components/Dashboard/Charts/DonutChart.vue
- src/components/Dashboard/Charts/LineChartPortfolio.vue
- src/components/Dashboard/Charts/LineChartTable.vue
- src/components/Dashboard/DashboardDonutChart.vue
- src/components/Dashboard/DashboardPage.vue
- src/components/Dashboard/DashboardTable.vue
- src/components/Signup.vue
- src/components/Wallets/Wallet.vue
- src/components/Wallets/WalletMenuItem.vue
- src/store/Dashboard.js
- tests/e2e/support/command.js
- tests/unit/store/Dashboard.spec.js
Right now, an entire list of all the assets Is shown to the user. The task is to check on Iroha side what wallets are non-empty and display only that information. Also need to fix several issues that was send in discord.
1. `yarn serve` and open the app.
> D3-392 | Fixing several dashboard issues

- src/components/Wallets/Wallet.vue
Need to fix bug that precision does not shown correctly
D3-478: Change columns
> D3-477, D3-478 | Fix precision in wallets history [Develop]

- src/components/Wallets/Wallet.vue
- src/util/store-util.js
Fix bug with withdrawal after renaming notary_red. 
https://soramitsu.atlassian.net/browse/D3-552
**WARNING**: Test can be conducted only after merging D3-551 task https://github.com/d3ledger/back-office/pull/86
2. `yarn serve` to run dev server
3. Test withdrawal function
> D3-552 | Web withdrawal fix - rename notary_red -> notary

- src/components/mixins/inputValidation.js
Fix validation for amount. A lot of zeros before amount should be invalid
2. `yarn` to run application
3. Go to wallet and try to transfer `000000.2`
> D3-685 | Fix validation for amount

- src/components/Wallets/Wallet.vue
- src/components/Wallets/WalletsPage.vue
- src/components/common/NoAssetsCard.vue
- src/store/Account.js
A user cannot browse any other wallets except the first network registered in due to probable frontend bug
https://soramitsu.atlassian.net/browse/D3-686
1. Run frontend
2. Register in BTC and ETH network
3. Add any amount of money to one wallet
4. Open wallets page
> D3 686 | Show empty wallet

- src/components/Home.vue
- src/components/Signup.vue
- src/components/Wallets/Wallet.vue
- src/components/mixins/inputValidation.js
- src/data/urls.js
Invalid representation regular expression during Log in
[a-Z_0-9] should be replaced on [a-z_0-9] if we consider only small letters
Add validation for additional information (no longer than 64 symbols)
Fix type EtherEum
Add space between Bitcoin registration and address.
https://soramitsu.atlassian.net/browse/D3-729
https://soramitsu.atlassian.net/browse/D3-716
1. Run frontend with backend
2. Try to login with login name with uppercases
3. Try to transfer/exchange money with additional information with message more than 64 symbols
4. Change one address in listOfNodes and registrationIPs to longer and check dropdowns in login and registration
> D3 729 | Fix validation message

- src/components/Dashboard/Charts/LineChartPortfolio.vue
- src/components/Dashboard/DashboardPortfolio.vue
When you point to the chart in the portfolio of history, Department integer part from the decimal displays the decimal point. At the same time, in the current price, the separation occurs through the point.
https://soramitsu.atlassian.net/browse/D3-723
1. Run
2. Open portfolio page on russian locale of browser
3. Check tooltips, portfolio value and portfolio history values in chart. They should had same format
> D3 723 | Fix number format

- src/components/mixins/inputValidation.js
We have wrong validation for private key
-  Any private key should be covered by [A-Fa-f0-9]{64}
> D3-812 | Correct regex

- src/components/Login.vue
https://soramitsu.atlassian.net/browse/D3-657
1. On running application clean localStorage and restart page. First node always should be selected
> D3-657 | Choose node on login

- docker/docker-compose-dev.yaml
- docker/docker-compose.yaml
- docker/iroha/config.docker
- package.json
- src/data/urls.js
- yarn.lock
This is a task about to migrate to iroha-rc3. Currently this PR is stoped and we will wait for iroha-rc4.
https://soramitsu.atlassian.net/browse/D3-887
> D3-887 | Update to iroha-rc4

- src/store/App.js
- src/util/iroha/commands.js
Added `clearSignaturesList` for correct handling of accepting \ rejecting settlements. We should call `clearSignaturesList` because otherwise transaction will be committed as new one.
> D3-1120 | Fix accept\reject of settlements
