package.json, scripts/setup-accounts-and-assets.js, src/App.vue, src/components/Home.vue, src/components/Login.vue, src/components/Settlements/SettlementsHistory.vue, src/components/Settlements/SettlementsPage.vue, src/components/Settlements/SettlementsWaiting.vue, src/components/Signup.vue, src/mocks/settlements.json, src/router.js, src/store/Account.js, src/util/iroha-util.js, src/util/store-util.js, tests/unit/fixtures/assets.json, tests/unit/helper.js, tests/unit/store/Account.spec.js, yarn.lock
* For now it just do sleep for a moment.
* Parameters are below:
* `username` is input by the user.
* `domain` is pre-defined.
* `publicKey` is automatically and internally generated by iroha-lib and sent to server.
* `privateKey` is generated along with the publicKey but not sent to server.
* For now it assumes a transaction to be part of a settlement and returns a dummy settlement if the message of the transaction is `'PART_OF_DUMMY_SETTLEMENT'`.
* Settlements in "Waiting" page are fetched by getAllUnsignedTransactions API.
* Settlements in "History" page are fetched by getAccountTransactions API.
* Note that these APIs are not fixed yet and might need changing according to their format.
* For now the actions just do sleep for a moment.
* For now the actions just do sleep for a moment. …
=> Registration, Settlements and Withdrawal (mock)

src/App.vue, src/components/Login.vue, src/components/Wallets/WalletsPage.vue, src/components/common/NoAssetsCard.vue
D3-129, D3-130
* Auto-add http if there is no other prefixes in node ip (needed for grpc-web)
* Username from filename
* Card, which shows where user should send money if he has no assets. We should use it at dashboard as well.
1. `yarn serve`
2. Login with `%secret-credentials-I-sent%`.
3. Enjoy.
=> Fix/d3 129/no wallets after registration

package.json, src/components/Dashboard/Charts/LineChartPortfolio.vue, src/components/Dashboard/Charts/LineChartTable.vue, src/components/Dashboard/DashboardPortfolio.vue, src/components/Dashboard/DashboardTable.vue, src/components/Settings/SettingsPage.vue, src/components/Settlements/SettlementsHistory.vue, src/components/Settlements/SettlementsIncoming.vue, src/components/Settlements/SettlementsOutgoing.vue, src/components/Wallets/Wallet.vue, src/components/mixins/currencySymbol.js, src/components/mixins/dateFormat.js, src/store/Settings.js, yarn.lock
**Task**: Add opportunity to change timezone. (Currently it's only local time zone)
- `timezones.json`
Time of the transaction should be shown in selected time zone.
1. `yarn` to install new packages.
2. `yarn rebuild` to rebuild native modules.
3. `yarn serve:electron` to launch the app.
=> Feature/settings-timezone - Add time zones

tests/unit/helper.js, tests/unit/store/Account.spec.js, tests/unit/store/Dashboard.spec.js, tests/unit/util/report-util.spec.js
We have fixed tests, broken by exports in iroha-util. Also, we have disabled reports test for now since there are problems with dates/prices.
Test skip for report-util. @oimou please fix this test later on ^^
=> Fix/tests broken by iroha-util

src/App.vue
Button has correct colors now :)
https://dist-bsfefugcqz.now.sh
=> D3-274 | Wrong colors of login button on hover

src/components/Home.vue, src/components/Transactions/TransactionPage.vue, src/main.js, src/router.js, src/store/Account.js, src/util/iroha-util.js, tests/unit/store/Account.spec.js
This PR contains two tasks
1. Implement markup for several signatures
2. Implement markup for pending transactions
To check it the amount of quorum should be more then 1. To review PR you should change quorum amount directly in `Account.js` store on line 160.
```javascript
state.accountQuorum = account.quorum + 2
```
1. `yarn` to install new packages.
2. `yarn serve` to run dev server.
=> D3-237, D3-232 | Add markup for pages

src/components/Wallets/Wallet.vue, src/components/mixins/numberFormat.js
The task is to show numbers with a lot of zeros after dot correctly
2. `yarn serve` to run development server
=> D3-364 | Now decimal numbers represented correctly

.eslintignore, docker/docker-compose-dev.yaml, package.json, src/components/Home.vue, src/components/Wallets/Wallet.vue, src/store/Account.js, src/util/iroha/commands.js, yarn.lock
Implemented "settlements creation" functionality. No "Settlements approval" or "History of settlements" for now.
Bonus: created `docker-compose-dev` to simplify tests.
1. Start docker
2. `yarn && yarn serve`
3. `node scripts/setup`
4. Login as `alice@notary` and try to create settlement.
5. Check that settlement appeared in Iroha (as batch of transactions).
* AssetID is not validated (you can send settlement w/o selected assetID)
* Now it is virtually impossible to create failing settlement, since it passes only stateless validation (with exception for settlement w/o assetID)
=> D3-138 | Settlements creation

src/components/Dashboard/DashboardTable.vue, src/components/Reports/ReportsPage.vue, src/components/Wallets/WalletsPage.vue
Fixed several issues that happened in PR #57.
=> D3-347 | Fixing pr #57

docker/docker-compose-dev.yaml, scripts/setup-accounts-and-assets.js, src/components/Home.vue, src/components/Transactions/TransactionPage.vue, src/components/mixins/inputValidation.js, src/store/Account.js, src/store/App.js, src/util/iroha/commands.js, src/util/store-util.js, tests/unit/fixtures/transactions.json
Now user is warned if he tries to sign a transaction with already used private key. Also, fixed some bugs.
1. `yarn && yarn serve`
2. `docker-compose -f docker/docker-compose-dev.yaml up`
3. Login with test@notary
4. Wallets -> Transfer -> Sign with test@notary
5. Transactions -> try signing with test@notary, see "this key is used", try with alice@notary
=> D3 388 | public keys validation

src/components/Dashboard/Charts/LineChartPortfolio.vue, src/components/Dashboard/Charts/LineChartTable.vue, src/components/Dashboard/DashboardChart.vue, src/components/Dashboard/DashboardTable.vue, src/components/Transactions/TransactionPage.vue, src/components/Wallets/Wallet.vue, src/main.js, src/store/Dashboard.js, tests/e2e/integration/reports.spec.js, tests/e2e/integration/wallets.spec.js, tests/e2e/support/command.js, tests/unit/store/Dashboard.spec.js
Added new chart for dashboard table. Fixed some issues with portfolio chart
1. `yarn` to install all dependecies
2. `yarn serve` to run dev server
=> D3-413 | Create candles chart 📈📈📈

src/components/Transactions/TransactionPage.vue, src/components/mixins/dateFormat.js
Right now our exchange orders and transaction batches have expiration time (24 hours since creation timestamp). The task is show timer, that would count down time for expiration
2. `yarn serve` to run dev server
=> D3-387 | Create expiration time for transaction

README.md
Update readme.md
1. Check file readme.md [Link to README.md](https://github.com/d3ledger/back-office/tree/feature/D3-465-readme)
=> D3-465 | Update README.md

README.md, src/components/Wallets/Wallet.vue
Need to fix bug that precision does not shown correctly
D3-478: Change columns
=> D3-477, D3-478 | Fix precision in wallets history

src/components/Wallets/Wallet.vue
Fix an issue with balance card on wallets page
=> D3-483 | Fit amount of tokens to card

src/store/Account.js
Need to fix bug with whitelist
2. Add more wallets to `setup-accounts-and-assets` on line 36.
3. `yarn serve` to run dev server
=> D3-514 | Bug with whitelist

docker/docker-compose-dev.yaml, docker/docker-compose.yaml, package.json, scripts/setup-accounts-and-assets.js, src/components/Dashboard/Charts/LineChartTable.vue, src/components/Home.vue, src/components/Settlements/SettlementsHistory.vue, src/components/Settlements/SettlementsIncoming.vue, src/components/Settlements/SettlementsOutgoing.vue, src/components/Transactions/TransactionPage.vue, src/components/Wallets/Wallet.vue, src/components/mixins/dateFormat.js, src/components/mixins/inputValidation.js, src/store/Account.js, src/store/App.js, src/util/iroha/commands.js, src/util/iroha/functions.js, src/util/iroha/queries.js, src/util/store-util.js, tests/e2e/integration/wallets.spec.js, tests/e2e/support/command.js
This task is about getting transaction bathes from GetPendingTransactions endpoint in Iroha.
2. `yarn server` to run application
=> D3-385 | Added exchange to D3

src/components/Home.vue, src/components/Settings/SettingsPage.vue, src/components/Transactions/TransactionPage.vue, src/components/Wallets/Wallet.vue, src/components/mixins/message.js
The task is about change message for incomplete transactions, when in signs less than quorum of signatures.
3. Make withdraw with less than quorum signatures
4. Make transfer with less than quorum signatures
5. Make transaction with less than quorum signatures and after on transactions page approve transaction less than quorum signatures
=> D3-588 | Message for incomplete transaction

src/App.vue, src/components/Dashboard/DashboardChart.vue, src/components/Dashboard/DashboardPortfolio.vue, src/components/Wallets/Wallet.vue, src/store/Dashboard.js, tests/unit/store/Dashboard.spec.js
https://soramitsu.atlassian.net/browse/D3-596
https://soramitsu.atlassian.net/browse/D3-597
https://soramitsu.atlassian.net/browse/D3-598
=> D3 596 597 598 | Interface changes

src/util/store-util.js
After a deposit performed there is a record in the EXCHANGE history:
undefined undefined -> <amount><currency> Invalid date
=> D3-655 | Fix bug with transaction shown in settlements

README.md, src/App.vue, src/components/Home.vue, src/components/Login.vue, src/components/Settings/SettingsPage.vue, src/components/Signup.vue, src/components/Wallets/Wallet.vue, src/components/common/NoAssetsCard.vue, src/data/enums.js, src/data/notaryIPs.json, src/data/urls.js, src/store/Account.js, src/store/App.js, src/util/crypto-list.json, src/util/notary-util.js
Tasks is about registration in bitcoin network and show bitcoin wallet address
3. Launch local bitcoin notary with registration (generate address)
4. Register in bitcoin network
=> D3 614-615 | Web bitcoin registration

src/components/Home/Menu.vue, src/main.js
The task is about to add numbers of transaction to menu
2 `yarn serve` to run app
3. Try to create settlement and check from another account. The amount of incoming should be shown in the badge. Also pending transaction should be shown.
=> D3-600 | Add badge to menu

src/components/Home.vue, src/components/Home/Menu.vue, src/components/Login.vue, src/components/Signup.vue, src/components/Transactions/TransactionPage.vue, src/components/Wallets/Wallet.vue, src/components/mixins/message.js, src/data/notaryIPs.json, src/data/notifications.js
The task is about to create human readable notifications. When transferring assets to the same account the user logged in OR when transferring assets to an account that does not exist in the system a user get a raw Iroha transaction exception.
3. Try to transfer assets to the same account or to an account that does not exist
=> D3-656 | Human readable messages

src/components/Dashboard/DashboardDonutChart.vue, src/components/mixins/currencySymbol.js, src/util/crypto-list.json
https://soramitsu.atlassian.net/browse/D3-707
https://soramitsu.atlassian.net/browse/D3-700
https://soramitsu.atlassian.net/browse/D3-703
1. Run frontend
2. Send any amount of tokens to empty account. 
3. Check asset name in settlements page
4. Add different assets to account, check color of others in portfolio donut chart 
5. Check Ether name (Should start from upper case)
=> D3 707, 700, 703 | Assets

src/components/Dashboard/Charts/LineChartPortfolio.vue
https://soramitsu.atlassian.net/browse/D3-748
1. Run
2. Open portfolio page, when all you assets has less than 1 in current fiat currency
=> D3 748 | Portfolio history amount y axis fix

src/util/report-util.js, tests/unit/fixtures/report.json
In downloaded report file there is no information about date and time. Moreover, there is wrong representation in description column
https://soramitsu.atlassian.net/browse/D3-752
1. Run
2. Try to download report in firefox browser
=> D3 752 | Fix date in report

src/components/Settlements/SettlementsIncoming.vue, src/components/Wallets/Wallet.vue
https://soramitsu.atlassian.net/browse/D3-725
https://soramitsu.atlassian.net/browse/D3-767
1. Run
2. Send exchange
3. Check text when accept exchange
4. Open wallet to check correct order of transactions
=> D3 767 | Grammar fix

src/components/mixins/inputValidation.js
https://soramitsu.atlassian.net/browse/D3-735
1. Run
2. Try to transfer some money with spaces before or after amount
=> D3 735 | Fix tokens amount validation error

src/components/Wallets/Wallet.vue
https://soramitsu.atlassian.net/browse/D3-750
1. Run
2. Open wallet with history
3. Click on transaction of different types
=> D3 750 | Change show more section in history

src/components/Home.vue
https://soramitsu.atlassian.net/browse/D3-768
1. Run
2. Open transfer dialog, input amount and address and click Transfer
3. Close confirmation dialog and click transfer again.
4. Choose private key file and send Confirm
=> D3 768 | Confirm not validate sometimes

src/store/Account.js
https://soramitsu.atlassian.net/browse/D3-820
- In settings page add new public key and then try to delete it
=> D3-820 | Bug with removing private keys

src/components/Wallets/Wallet.vue
Delete re-description of the address in the Column  [Description] and when clicking on the expanding  arrow
https://soramitsu.atlassian.net/browse/D3-818
1. Run 
2. Withdraw any amount of money
3. Deposit any amount of money
=> D3 818 | Remove withdrawal description

src/App.vue, src/components/Settings/SettingsPage.vue, src/main.js
https://soramitsu.atlassian.net/browse/D3-764
- Go to settings page
=> D3-764 | Implement design of limits

docker/docker-compose-dev.yaml, docker/docker-compose.yaml, src/components/Wallets/Wallet.vue, src/main.js
https://soramitsu.atlassian.net/browse/D3-817
- Go to wallets page. At the end of history should be pagination
=> D3-817 | Add pagination (design)

src/App.vue, src/components/Settlements/SettlementsHistory.vue, src/components/Wallets/Wallet.vue, src/components/Wallets/WalletsPage.vue, src/store/Account.js, tests/unit/store/Account.spec.js
The task is to create logic for pagination
https://soramitsu.atlassian.net/browse/D3-822
- Go to wallets page and check pagination system
=> D3-822 | Create logic for pagination

src/components/Wallets/Wallet.vue
https://soramitsu.atlassian.net/browse/D3-659
0. `yarn serve`
1. Open wallet page on first account
2. Open wallet page on second account
3. Send some tokens from first to second
4. Press refresh on second account
=> D3 659 | Refresh button

public/sw.js, src/components/Home.vue, src/components/Settings/SettingsPage.vue, src/main.js, src/store/Account.js, src/util/push-util.js
https://soramitsu.atlassian.net/browse/D3-859
0. run frontend `yarn serve`
1. run backend with notification server
2. Enable notifications in settings
3. Make transaction
=> D3 859 | Push notifications

src/components/Home.vue, src/components/common/modals/ConfirmModal.vue, tests/e2e/integration/settings.spec.js, tests/e2e/integration/wallets.spec.js, tests/e2e/support/command.js
https://soramitsu.atlassian.net/browse/D3-801
=> D3-801 | Countdown

src/components/Dashboard/DashboardPage.vue, src/components/Home.vue, src/components/Wallets/WalletsPage.vue, src/util/cryptoApi-axios-util.js
1. Remove address of crypto currency API
2. `yarn serve`
3. Check wallet and dashboard pages
=> D3 873 | Fix market data lack

docker/iroha/genesis.block, package.json, src/components/Home.vue, src/components/Wallets/Wallet.vue, src/components/mixins/inputValidation.js, tests/e2e/integration/wallets.spec.js
https://soramitsu.atlassian.net/browse/D3-755
0. Run
1. Try to send some money to unregistered account
2. Try to send some money to registered account
3. Try to make exchange with unregistered account
4. Try to make exchange with registered account
=> D3 755 | Prevent exchange to unregistered uset

scripts/setup-accounts-and-assets.js, src/App.vue, src/components/Home.vue, src/components/Home/Menu.vue, src/components/Settings/SettingsPage.vue, src/components/Transactions/TransactionPage.vue, src/components/Wallets/Wallet.vue, src/components/common/modals/ConfirmModal.vue, src/store/Account.js, src/util/iroha/queries.js, tests/e2e/integration/reports.spec.js, tests/e2e/support/command.js, tests/unit/store/Account.spec.js
https://soramitsu.atlassian.net/browse/D3-212
**On local machine:**
Every time when I run test of reports page it works correctly. All methods for file downloading works fine
**On jenkins:**
Sometimes any test of downloading PDF or CSV file can fail without any reason.
=> D3-212 | Update test

src/components/Signup.vue, src/components/common/NoAssetsCard.vue, src/data/urls.js, tests/e2e/integration/auth.spec.js
https://soramitsu.atlassian.net/browse/D3-889
0. Run full
1. Register
2. Add eth/btc wallet in settings
=> D3 889 | New registration

src/util/report-util.js
https://soramitsu.atlassian.net/browse/D3-814
=> D3-814 | Update report

package.json, src/App.vue, src/components/Home.vue, src/components/Login.vue, src/components/Signup.vue, src/components/Wallets/Wallet.vue, src/components/common/modals/ConfirmModal.vue, src/components/common/modals/ExchangeModal.vue, src/components/mixins/validation.js, src/data/urls.js, src/main.js, src/store/Account.js, tests/e2e/integration/auth.spec.js, tests/e2e/integration/settings.spec.js, yarn.lock
https://soramitsu.atlassian.net/browse/D3-860
=> D3-860 | Update validation forms

src/components/mixins/validation.js
=> Hotfix | Remove user exist

src/components/Dashboard/DashboardPortfolio.vue, src/components/Settings/SettingsPage.vue, src/components/mixins/dateFormat.js, src/store/Dashboard.js, tests/unit/store/Dashboard.spec.js
https://soramitsu.atlassian.net/browse/D3-721
0. Run
1. Open portfolio page
2. Try to change Portfolio history range
3. Check that difference changed
=> D3 721 | Fix difference from last period of portfolio price

src/components/Dashboard/DashboardPortfolio.vue
=> Hotfix D3 721  | difference message 

public/relays.json, src/App.vue, src/components/Settings/SettingsPage.vue, src/components/Signup.vue, src/data/urls.js, src/store/Account.js, src/store/App.js, src/util/notary-util.js
https://soramitsu.atlassian.net/browse/D3-1013
=> D3-1013 | Add config file for relays

docker/docker-compose-dev.yaml, docker/docker-compose.yaml, scripts/setup-accounts-and-assets.js, src/components/Explorer/ExplorerPage.vue, src/components/Reports/ReportsPage.vue, src/components/Settings/SettingsPage.vue, src/components/Settings/components/WalletLimitsCard.vue, src/components/Wallets/Wallet.vue, src/components/mixins/validation.js, src/data/consts.js, src/store/Account.js
1. Introduce an ability to remove whitelists
2. Introduce an ability to add whitelists
3. Update whitelists representation (we need to mark pending requests as "Pending")
0. Run
1. Register in btc and eth network
2. Add white addresses in settings page
3. Wait 3 days (or change ADDRESS_WAITING_TIME)
4. Try to withdraw
=> D3 991 | Whitelists

public/nodes.json, public/registrations.json, public/relays.json, src/components/Settings/SettingsPage.vue, src/components/Settings/components/WalletLimitsCard.vue, src/util/iroha/functions.js, src/util/notary-util.js
https://soramitsu.atlassian.net/browse/D3-1034
=> D3-1034 | Dynamic selection of protocol for configs

docker/iroha/genesis.block, scripts/setup-accounts-and-assets.js, src/App.vue, src/components/Login.vue, src/components/common/modals/ExchangeModal.vue, src/data/wallets.json, src/store/Account.js, tests/e2e/integration/reports.spec.js, vue.config.js
The task was to correct tests that crashes from time to time. Also I added several features into the system.
=> D3-1041 | Fix tests and other minor fixes

Dockerfile, src/components/Reports/ReportsPage.vue, src/util/report-util.js
https://soramitsu.atlassian.net/browse/D3-888
=> D3-888 | Update report system

src/components/Settlements/SettlementsIncoming.vue, src/store/Account.js, src/store/Settings.js, src/util/iroha/commands.js, tests/unit/store/Account.spec.js
Fix exchange 
0. Run
1. Try to make exhcange
=> Fix exchange

src/util/notary-util.js
Hot fix for protocol selection #162
=> Protocol selection | fix #162

src/util/iroha/util.js, src/util/notary-util.js
Hot fix for protocol selection #162 
Corrected issue with iroha connection
=> Protocol selection 2 | fix #162

src/components/common/modals/ExchangeModal.vue
Now market price calculated based on user input
**OLD**
**NEW**
If you do not see the difference look at market price 😄
=> D3-1056 | Great exchange update 🎉🎉🎉

src/components/Dashboard/DashboardPage.vue, src/components/Dashboard/DashboardPortfolio.vue, src/components/Explorer/ExplorerPage.vue, src/components/Fee/FeePage.vue, src/components/Home.vue, src/components/Home/Menu.vue, src/components/Reports/ReportsPage.vue, src/components/Settings/SettingsPage.vue, src/components/Settlements/SettlementsPage.vue, src/components/Transactions/TransactionPage.vue, src/components/Wallets/Wallet.vue, src/components/Wallets/WalletsPage.vue
The task is about to update menu to static format and change size of the pages to full screen.
This PR will be merged only after #170.
=> D3-1055 | Update styles of menu and pages

package.json, public/config.json, src/components/Fee/FeePage.vue, src/components/Home.vue, src/components/common/modals/ExchangeModal.vue, src/components/mixins/currencySymbol.js, src/store/Account.js, src/store/App.js, src/util/collector-util.js, src/util/config-util.js, src/util/iroha/commands.js, src/util/store-util.js, tests/e2e/integration/wallets.spec.js, tests/unit/store/Account.spec.js, yarn.lock
Added ability to work with assets that was added in admin panel
This PR is based on https://github.com/d3ledger/back-office-admin/pull/4
=> D3-1057 | Ability to work with new assets

Jenkinsfile, package.json, yarn.lock
=> D3-1056-3 | Update iroha-helpers version

src/components/Dashboard/DashboardPage.vue
=> D3-1057 | Update text on card

src/components/Signup.vue, src/components/mixins/message.js, src/main.js, src/store/Account.js
This PR added ability to register with own public key
=> D3-1062 | Registration with own public key

src/store/Account.js
Fixed bug with exchanges with bitcoin and xor tokens
=> D3-1085 | Fix naming of bitcoin

src/util/iroha/commands.js
Need to handle 2 statutes from iroha for correct reject
=> D3-1077 | Fix issue with rejecting exchange

src/store/Dashboard.js
Dashboard should show all correct assets that work with api
=> D3-1093 | Fix dashboard

package.json, src/components/Settings/components/Rightside/QuorumCard.vue, yarn.lock
Updated library.
Removed the MST_EXPIRED status from terminal statuses.
=> D3 FIX | MST_EXPIRED

package.json, yarn.lock
Updated version of iroha-helpers for logs in console
=> feat: update helpers for status log

package.json, yarn.lock
=> chore: update version

src/components/Settings/SettingsRightSide.vue, src/components/Settings/components/Rightside/CustomTxCard.vue, src/store/App.js, src/util/iroha/commands.js
https://soramitsu.atlassian.net/browse/D3-1063
Need to add custom input for sending transactions that was generate offline
=> D3-1063 | Add ability for uploading custom tx

src/components/Wallets/Wallet.vue
Change name of transfer function in withdrawal method
=> Fix | Withdrawal function

src/components/Wallets/Wallet.vue, src/components/common/modals/ExchangeModal.vue, src/components/mixins/validation.js, src/main.js
=> Fix | Config max decimal numbers

src/components/Wallets/Wallet.vue, src/components/common/modals/ExchangeModal.vue, src/components/mixins/validation.js, src/store/Account.js, src/util/billing-util.js, src/util/collector-util.js, tests/e2e/fixtures/data-collector-api/user.json, tests/e2e/integration/wallets.spec.js
Added validation for account name. Added request to API for receiver quorum.
=> D3-1107 | Check account name and set quorum

src/App.vue, src/components/Login.vue, src/components/Settings/components/Rightside/WalletLimitsCard.vue, src/components/common/modals/ConfirmModal.vue
Fixed a style error of input fields in Safari browser. Also added type password for private keys
Old
New
=> FIX Style | Update of styles for safari browser

src/components/Wallets/Wallet.vue, src/store/Account.js, src/util/store-util.js
https://soramitsu.atlassian.net/browse/D3-1103
=> D3-1103 | Changed msg type to `withdrawal`

src/components/Reports/BillingReportsPage.vue, src/components/Signup.vue, src/store/Account.js
feat: add cypress section in key download on registration
fix: make billing reports page full-width
fix: update custody billing format
=> D3 1122 | Update for tests

src/components/Settings/components/Rightside/QuorumCard.vue, src/store/Account.js
https://soramitsu.atlassian.net/browse/D3-1125
=> D3-1125 | Remove quorum updating

src/components/Settings/components/Rightside/SettingsCard.vue
Need to update styles in safari browser
https://soramitsu.atlassian.net/browse/D3-1126
=> D3-1126 | Fixed styles in safari browser

src/components/Wallets/components/modals/WithdrawalModal.vue, src/data/consts.js, src/util/iroha/commands.js, src/util/store-util.js
https://soramitsu.atlassian.net/browse/D3-1128
=> D3-1128 | Update withdrawal method

src/components/Settings/components/Leftside/NotificationsItem.vue, src/store/Account.js
Add email configuration for notifications in settings
=> Feature | Add email notifications

src/components/Signup.vue, src/components/Wallets/components/InfoCards.vue, src/components/Wallets/components/modals/TransferModal.vue, src/components/Wallets/components/modals/WithdrawalModal.vue, src/components/common/modals/ExchangeModal.vue, src/data/consts.js, src/store/Account.js, src/store/App.js, src/util/billing-util.js
1. Update get billing info
2. Mandatory public key in registration
=> Feature |  mandatory public key in registration

src/components/Signup.vue, src/util/notary-util.js, tests/e2e/integration/auth.spec.js
=> D3 | Added domain to signup

src/store/Account.js
Fix d3 registration with domain
=> D3 | Fix registration in d3-eth | d3-btc

src/store/Account.js
Removed static brvs name for dynamic based on account domain.
=> D3 | Fix dynamic brvs naming

src/components/Wallets/components/InfoCards.vue, src/components/common/modals/ExchangeModal.vue, src/store/Account.js, src/store/App.js, src/util/iroha/commands.js, src/util/store-util.js
If you you need set fee, you should to have an account like `admin@DOMAIN`. `DOMAIN` is domain of registration service.
```
environment:
- REGISTRATION_DOMAIN=d3
```
=> D3-1182 | Fix fee transaction

src/store/Account.js, tests/unit/store/Account.spec.js
Get account quorum then user login
=> D3 | Fix quorum

package.json, scripts/generateTx.js, src/App.vue, src/components/Home.vue, src/components/Transactions/TransactionPage.vue, src/components/Transactions/components/SettingsTab.vue, src/components/Transactions/components/TransferTab.vue, src/store/Account.js, src/util/iroha/queries.js, src/util/store-util.js, yarn.lock
Added new transaction view for several transactions in one command
=> D3 | Transaction view

src/components/Wallets/components/modals/TransferModal.vue, src/components/Wallets/components/modals/WithdrawalModal.vue, src/components/common/modals/ExchangeModal.vue, src/store/Account.js
Corrected errors that happend due to migration to SoraNet
=> D3 | Bug fixes
